camel:
  grpc-port: 8080
  springboot:
    main-run-controller: true

spring:
  application:
    name: user-service
  datasource:
    url: 'jdbc:postgresql://172.16.229.217:5432/microibdb?currentSchema=grpc'
    username: 'microib'
    password: 'microib@23'
  jpa:
    database: postgresql
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: 'grpc'
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:/db/liquibase/db.changelog-master.xml
    liquibase-schema: ${spring.jpa.properties.hibernate.default_schema}

logging:
  level:
    org.apache.camel: info