camel:
  grpc-port: 8080
  springboot:
    main-run-controller: true

spring:
  application:
    name: user-service
  datasource:
    url: 'jdbc:h2:file:${user.home}/.grpc/${spring.application.name}/v100'
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ~
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:/db/liquibase/db.changelog-master.xml
    liquibase-schema: ${spring.jpa.properties.hibernate.default_schema}

logging:
  level:
    org.apache.camel: info