server:
  name: user-service
  version: 1.0.0
  port: ${SERVER_PORT:8080}
  servlet-context-path: '/api/v1/user'

spring:
  application:
    name: ${server.name}
  autoconfigure:
    exclude: org.apache.camel.spring.boot.security.CamelSSLAutoConfiguration

camel:
  springboot:
    name: ${server.name}
    main-run-controller: true

logging:
  level:
    org.apache.camel: info